obj = {
'Arsenal FC' :4,
'Aston Villa FC':10,
'Brentford FC':17,
'Brighton & Hove Albion FC':10,
'Burnley FC':17,
'Chelsea FC':1,
'Crystal Palace FC':10,
'Everton FC':10,
'Leeds United FC':10,
'Leicester City FC':6,
'Liverpool FC':1,
'Manchester City FC':1,
'Manchester United FC':4,
'Newcastle United FC':17,
'Norwich City FC':17,
'Southampton FC':10,
'Tottenham Hotspur FC':6,
'Watford FC':17,
'West Ham United FC':4,
'Wolverhampton Wanderers FC':6,
}
